name: Export

on:
    push:
        branches:
            - "*"
        tags:
            - "v*.*.*"
    pull_request:
        branches:
            - "*"

env:
    GODOT_VERSION: 4.4
    BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-22.04  # Use 22.04 with godot 4
    container:
      image: barichello/godot-ci:4.4
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
    - name: export game
      run: |
          mkdir -v -p export
          EXPORT_DIR="$(readlink -f export)"
          godot --headless --verbose --export-release "Web" "./export/index.html"
    - name: Butler push
      run: ./butler_push.sh